- .github/ISSUE_TEMPLATE/scrum-report---.md
just a template so we can quickly create the scrum reports threads and remind ourselves of requirements
> template for future scrum reports

- client/src/App.jsx
- client/src/components/Navbar.jsx
- client/src/index.jsx
- client/src/pages/About.jsx
- client/src/pages/Home.jsx
- client/src/pages/Profile.jsx
Responsive, global navigation bar that routes to different dummy pages based on the link that you click. 
See the component here:
https://mui.com/material-ui/react-app-bar/#ResponsiveAppBar.js
Recored with [screentogif](https://www.screentogif.com/).
> feat: implement global nav bar with routing

- client/package-lock.json
- client/package.json
- client/src/components/Navbar.jsx
- client/src/index.jsx
- client/src/pages/Landing.jsx
**Responsive landing page** with a video background, uses a [typewriter package](https://www.npmjs.com/package/typewriter-effect).
In our next meeting we should decide on a set of fonts and a color theme to work with. 
I have a linter error that I can't solve, if anyone could checkout the branch and see what's up that would be appreciated! (see error below)
> feat: implement landing page

- client/public/index.html
- client/src/App.jsx
- client/src/index.jsx
- client/src/pages/DesignLibrary.jsx
- client/src/styled.js
- client/src/theme.js
Sets up theme and resuable styled components. Will remove example styles in `styled.js` once no longer needed.
> Setup theme and reusable styles

- client/src/components/Profile/AdditionalProfileForm.jsx
- client/src/components/Profile/Forms/Form.jsx
- client/src/components/Profile/Forms/FormDatePicker.jsx
- client/src/components/Profile/Forms/FormMultiInput.jsx
- client/src/components/Profile/Forms/FormMultiSelect.jsx
- client/src/components/Profile/Forms/FormSelect.jsx
- client/src/components/Profile/Forms/FormTextFieldInput.jsx
- client/src/components/Profile/Forms/GridInputLabel.jsx
- client/src/reducers/AdditionalProfile.js
In this PR:
* Multi-input textfield
* Percentage restricted textfield
* Fix pressing "Enter" submits form
* refactor `GridInputLabel` since all forms were using same `InputLabel` and `Grid` 
* Added Redux initialization for newly added form components `workoutDuration`, `bodyFatPercentage`, `muscleMassPercentage`, `exercisePreferences`, `equipmentAvailability`
* implemented all the data under [CONFLUENCE User Data + Components](https://l1b-homies.atlassian.net/wiki/spaces/SD/pages/edit-v2/1441793)
*
> Update Profile - Final inputs

- client/src/actionCreators/MealPlan.js
- client/src/components/Home/ChatArea.jsx
- client/src/components/Home/PlanView/ExistingFitnessPlan.jsx
- client/src/components/Home/PlanView/FitnessPlanView.jsx
- client/src/components/Home/PlanView/NoFitnessPlan.jsx
- client/src/reducers/MealPlan.js
- client/src/reducers/index.js
What:
- "Create My Fitness Plan" button in NoFitnessPlan.jsx changes component to ExistingFitnessPlan.jsx, fetching initial fitness plan
- Improved styling for Fitness Plan with proper List via mui
- Reducer & mock initial plan created for Meal Plan
TODO:
- Change workflow in NoFitnessPlan.jsx to display confirmation popup prior to creating fitness plan and to use thunks
- Redesign the home page once figma design approved
> Fitness Plan Styling & Meal Plan Redux

- server/src/controllers/userProfileController.js
- server/src/routes/MealSchedule.js
- server/src/routes/UserProfile.js
- server/src/routes/WorkoutSchedule.js
- Implement UserProfileController
- adding some additional documentation on router
Note:
- GetAllProfile might a security concern, don't think we should give access to all profiles
- Delete might not need, should we have profile live for ever?
> Implement userProfileController

- server/src/controllers/userInfoController.js
- server/src/routes/UserInfo.js
API to delete account
- bulk delete in UserInfo, UserProfile, MealSchedule, WorkoutSchedule
- Return _id and email
Note:
- Other option is have a toggle in UserInfo, and preserve existing user information when user register again
> implement delete account

- server/package-lock.json
- server/package.json
- server/src/controllers/userProfileController.js
- server/src/routes/UserProfile.js
Prepare BE for profile image upload and update
Following the [article](https://blogs.yasharyan.com/store-images-on-mongodb) on storing image in MongoDB
Request frontend testing using the following format or equivalent to our own environment
`<form action="/userProfile" method="post" enctype="multipart/form-data">
<input type="file" name="image" /></form>`
Image should be able to display using the following format
`<img
src="data:<%=userProfile.profileImage.contentType%>;base64,
<%=userProfile.profileImage.data.toString('base64')%>"
/>`
> prepare BE for profile image upload and update

- client/package-lock.json
- server/package-lock.json
- server/src/controllers/mealScheduleController.js
- server/src/controllers/workoutScheduleController.js
Seems like linter is not working properly from another computer. Using another PC catches these small problems.
> Small lint fixes

- server/src/controllers/mealScheduleController.js
- server/src/controllers/workoutScheduleController.js
- server/src/routes/MealSchedule.js
- server/src/utils/prompts/mealPrompts.js
- server/src/utils/prompts/workoutPrompts.js
Meal schedules now include macros!
```
{
"schedule": {
"Monday": {
"breakfast": "Oatmeal with berries and almond butter",
"snack1": "Greek yogurt with mixed nuts",
"lunch": "Grilled chicken breast with quinoa and roasted vegetables",
"snack2": "Protein shake with banana",
"dinner": "Salmon with sweet potato and steamed broccoli",
"nutrition_totals": {
"calories": 2000,
"carbohydrates": 200,
"protein": 180,
"fat": 60
}
}...
```
> feat: implement macros in meal schedule and refactoring

- server/src/routes/MealSchedule.js
- server/src/routes/WorkoutSchedule.js
- server/src/utils/prompts/workoutPrompts.js
Sample formatted JSON output:
Full API output:
`{
"userInfoID": "64b2c71a9a5be8209313f217",
"schedule": "{\n  \"Monday\": {\n    \"exercises\": [\n      {\n        \"exercise\": \"Chest press\",\n        \"sets\": 3,\n        \"reps\": 10,\n        \"rest\": 60,\n        \"duration\": 20,\n        \"intensity\": 70,\n        \"calories\": 150\n      },\n      {\n        \"exercise\": \"Lat pulldown\",\n        \"sets\": 3,\n        \"reps\": 10,\n        \"rest\": 60,\n        \"duration\": 20,\n        \"intensity\": 70,\n        \"calories\": 120\n      },\n      {\n        \"exercise\": \"Squats\",\n        \"sets\": 3,\n        \"reps\": 12,\n        \"rest\": 60,\n        \"duration\": 15,\n        \"intensity\": 80,\n        \"calories\": 100\n      },\n      {\n …
> feat: add exercise and daily calorie counts

- client/package-lock.json
- server/src/controllers/workoutScheduleController.js
fix the bugs that results in existing fitness and meal schedules display in FE
> quick FE display profile bug fix

- server/src/controllers/userProfileController.js
- server/src/utils/openaiUtil.js
GPT API key verification:
- Verification done by making a GET request to the usage endpoint
- Date param is required
- - The actual date doesn't seem to matter, tested using random dates from 2020 to 2023
- Initial testing done by using postman
- - Returns error when using an invalid key
- - Returns a response when using valid key
- Missing case:
- - Unsure what the response will be if the api key doesn't have any funds or has outstanding bills
> API key verification

- server/postman/AIRON.postman_collection.json
- server/src/controllers/mealSchedule/mealScheduleController.js
- server/src/controllers/scheduleGenerationController.js
- server/src/controllers/workoutSchedule/mockMealScheduleController.js
- server/src/controllers/workoutSchedule/mockWorkoutAndMealSchedule.js
- server/src/controllers/workoutSchedule/mockWorkoutScheduleController.js
- server/src/controllers/workoutSchedule/workoutScheduleController.js
- server/src/routes/MealSchedule.js
- server/src/routes/UserProfile.js
- server/src/routes/WorkoutSchedule.js
- server/src/routes/mock.js
- server/src/utils/openaiUtil.js
- server/src/utils/prompts/workoutPrompts.js
- server/src/utils/userUtil.js
For @kennyjhcheng's tabbed view integration, a single API that provides both schedules back. 
A private route that requires authentication.
Access with `userprofile/generate`. 
Workout Schedule Macros available:
> calories PER exercise
> total calories PER day
Meal Schedule Macros available:
> calories, carbs, protein, fat PER day
Docs:
```
/**
* @desc generate workout and meal schedules based on user profile information
* @access Private
* @route POST /userProfile/generate
* @request
*  body: n/a
*  params: n/a
*  query params: n/a
* @response object containing both schedules
* {
*  "userInfoID": string,
*  "workoutSchedule": {
*    "Monday": {
*       "exercises": [
*          ...
*        ],
*       "total_calories"
*    }, ...
*   },
*  "mealSchedule" {
*    "Monday": {
* …
```
> feat: implement parallel schedule generation and refactoring

- package.json
- server/app.js
Initial setup for deploy, please verify the command
potential frontend name: "https://airon-fitness.onrender.com/"
> Initial deploy setup

- client/package-lock.json
- client/package.json
- client/src/components/Home/PlanView/TabbedScheduleView.jsx
- client/src/components/Profile/AdditionalProfileForm.jsx
- client/src/components/Profile/BasicProfileForm.jsx
- client/src/components/Profile/Forms/FormDatePicker.jsx
- client/src/components/Profile/Forms/FormMultiInput.jsx
- client/src/components/Profile/Forms/FormMultiSelect.jsx
- client/src/components/Profile/Forms/FormSelect.jsx
- client/src/components/Profile/Forms/FormTextFieldInput.jsx
- client/src/components/Profile/Forms/FormTextWithRadio.jsx
- client/src/components/Signup/SignupAPIKey.jsx
- client/src/components/Signup/SignupAdditionalDetails.jsx
- client/src/components/Signup/SignupBasicUserDetails.jsx
- client/src/components/Signup/SignupRegisterAccount.jsx
- client/src/components/Signup/SignupRequireUserDetails.jsx
- client/src/components/common/TabPanel.jsx
- client/src/components/common/context/ToastContextProvider.jsx
- client/src/pages/Login.jsx
- client/src/pages/Profile.jsx
* Using libraries `Formik` for better form state management and `Yup` for validation.
* Refactored signup and updating profile pages to have validation and use formik if needed
* form components have some additional props to support formik, but still work if used like the old way.
* update profile page using tabs
> Form validation with Formik + Yup and Tabbed update profile view

- client/src/App.jsx
- client/src/components/Navbar.jsx
- client/src/components/Profile/AvatarUpload.jsx
- client/src/components/Profile/Forms/FormMultiSelect.jsx
- client/src/components/Signup/SignupAdditionalDetails.jsx
- client/src/reducers/UserProfile.js
- client/src/services/UserProfileService.js
- server/src/controllers/userProfileController.js
In this PR:
* FE convert binary image data from BE to base64 and display
* display in navbar
* all avatar icons use letter of first name if no profile image
* max image size of 0.5MB checked client-side
* UserProfile reducer + service new thunk for user profile
https://github.com/jakji93/airon-fitness/assets/67628346/2b9f859f-c7f5-411b-8e99-09f27b3e1ed2
> User Profile End to End Integration

- server/app.js
see if remove localhost will resolve the issue
> [BUG] attempt resolve cors issue

- server/app.js
[BUG] Fitness + Meal Schedule not clearing from redux pr reverted this fix
> cors error fix again

- client/src/components/Profile/BasicProfileForm.jsx
- client/src/pages/Profile.jsx
> Profile Page error message when API key invalid

- client/src/components/Home/PlanView/ExistingMealSchedule.jsx
- client/src/components/Home/PlanView/ExistingWorkoutSchedule.jsx
- client/src/components/Home/StatsView/ExistingStatsView.jsx
- client/src/components/Home/StatsView/StatsView.jsx
- client/src/services/WorkoutAndMealScheduleService.js
- server/src/controllers/mealSchedule/mealScheduleController.js
- server/src/controllers/scheduleGenerationController.js
- server/src/controllers/workoutSchedule/workoutScheduleController.js
- server/src/utils/prompts/mealPrompts.js
Using the existing route for generating both schedules
> Update to use real data

- client/src/components/Navbar.jsx
- client/src/index.jsx
- client/src/pages/About.jsx
- client/src/theme.js
-About us
-meet the team
-disclaimer
initial styling done by Kevin
> About page

- client/src/components/Home/ChatArea.jsx
- client/src/components/Home/PlanView/TabbedScheduleView.jsx
- client/src/components/Home/StatsView/ExistingStatsView.jsx
- client/src/components/Home/WorkoutTable.jsx
- client/src/components/Profile/AvatarUpload.jsx
- client/src/components/Profile/BasicProfileForm.jsx
- client/src/components/Profile/Forms/Form.jsx
- client/src/components/Profile/Forms/FormDatePicker.jsx
- client/src/components/Profile/Forms/FormMultiInput.jsx
- client/src/components/Profile/Forms/FormMultiSelect.jsx
- client/src/components/Profile/Forms/FormSelect.jsx
- client/src/components/Profile/Forms/FormTextFieldInput.jsx
- client/src/components/Profile/Forms/FormTextWithRadio.jsx
- client/src/components/Profile/Forms/GridInputLabel.jsx
- client/src/components/Profile/Forms/PaperForm.jsx
- client/src/components/Signup/SignupAPIKey.jsx
- client/src/components/Signup/SignupRegisterAccount.jsx
- client/src/components/Signup/SignupRequireUserDetails.jsx
- client/src/pages/Home.jsx
- client/src/pages/Login.jsx
- client/src/pages/Profile.jsx
- client/src/pages/SignupFlow.jsx
- client/src/theme.js
What:
- Existing theme for application, including the chart colors in the statistics component, was not in alignment
- Additional component with Davis's implementation of Workout Table
How:
- Add units to charts inside the statistics component
- Implement grey background throughout the application
- Update forms to maintain visibility with implementation of grey background
- Align the components on the home page to all use the Grid layout to improve consistency
- Update placeholder for numerical input to 0
- Add skeleton component for Davis's implementation of Workout Table
TODO:
- Update styling for About page via Jack's PR
- Improve styling for Chat Area, which will be done after Kevin W's changes being merged into main.
> Application Styling

- client/src/components/Navbar.jsx
- client/src/pages/Profile.jsx
> [BUG][FAST-REVIEW] navbar double click + tab styling profile page

- client/src/components/Home/ChatArea/ChatArea.jsx
- client/src/components/Profile/BasicProfileForm.jsx
- client/src/components/Signup/SignupAPIKey.jsx
- client/src/components/Signup/SignupAdditionalDetails.jsx
- client/src/components/Signup/SignupBasicUserDetails.jsx
- client/src/components/Signup/SignupRegisterAccount.jsx
- client/src/components/Signup/SignupRequireUserDetails.jsx
- client/src/constants/BasicProfile.js
- client/src/pages/SignupFlow.jsx
- server/src/controllers/mealSchedule/mealScheduleController.js
- server/src/controllers/workoutSchedule/workoutScheduleController.js
Surround JSON.parse with try/catch block
Invalid schedule data shouldn't be saved in DB
Return 400 for invalid data
Typo fix in chat bot
metric unit on left and default selected on register
top inactive text to white
gold buttons
> JSON Parse error handling

- client/src/components/Home/ChatArea/ChatArea.jsx
- client/src/components/Home/PlanView/TabbedScheduleView.jsx
- client/src/components/Home/StatsView/StatsView.jsx
- client/src/pages/Home.jsx
Changes:
- Initial `useEffect` to fetch schedules in the tiles has been refactored to the home page component, shows a spinner while the request completes. Should reduce the number of duplicate requests
- Adds a slide fade in animation effect to the tiles
https://github.com/jakji93/airon-fitness/assets/66554168/ee8d8e51-df71-4bba-933b-ad1e3a7597a2
> Add home page animation

- client/src/pages/Home.jsx
- client/src/reducers/WorkoutAndMealSchedule.js
- client/src/services/util.js
Browser notification when request is done. Works for create + updating plans.
The pop-up depends on the notification settings the browser has.
My mac sometimes pops up a banner, sometimes it just leaves it in the notification area... not sure why
Try it out on ur computer, anyways not a big deal if they don't get notifications cuz it's behaving buggy, but cool to have the feature when it does work.
https://github.com/jakji93/airon-fitness/assets/67628346/c6d133db-c1d2-4117-85ad-2a4a5256c5d5
> Browser Notification + Request Permission

- client/src/components/Profile/Forms/FormSelect.jsx
- client/src/components/Profile/Forms/FormTextFieldInput.jsx
- client/src/components/Signup/SignupRegisterAccount.jsx
https://l1b-homies.atlassian.net/browse/QK455-112?atlOrigin=eyJpIjoiZTUxYjRiNDI5OTM2NDEzOWI4ZGY0NTdhNjEyNmUxZWUiLCJwIjoiaiJ9
* When user submits existing email, button gets disabled, if they start changing the email, button is enabled again
* Also subtle styling change for just `FormTextFieldInput`
* the label is contained within textbox
* the bottom bar is gold when clicked
https://github.com/jakji93/airon-fitness/assets/67628346/4de9a290-68f1-4a48-b98d-5e109efa451d
> [BUG] create account button disabled

- client/src/components/Profile/AdditionalProfileForm.jsx
- client/src/components/Profile/AvatarUpload.jsx
- client/src/components/Profile/BasicProfileForm.jsx
Updating Profile page button color based on UI thread
> update button color in profile

- client/src/components/Profile/Forms/FormDatePicker.jsx
- client/src/components/Profile/Forms/FormMultiInput.jsx
- client/src/components/Profile/Forms/FormMultiSelect.jsx
- client/src/components/Profile/Forms/FormSelect.jsx
- client/src/components/Profile/Forms/FormTextFieldInput.jsx
- client/src/theme.js
Form fields are
* border radius 4px
* Styled so the label doesn't go outside of the form field `variant=filled`
> [STYLE] Restyle form fields

- client/src/components/Navbar.jsx
> [STYLING] Navbar repsonsive drawer + Settings

- client/public/index.html
- client/src/components/Home/ChatArea/ChatArea.jsx
- client/src/components/Home/StatsView/ExistingStatsView.jsx
- client/src/components/Navbar.jsx
- client/src/components/Profile/AvatarUpload.jsx
- client/src/components/Signup/SignupBasicUserDetails.jsx
Just a series of style touchups. 
Leave this blue. Looks good in current state.
> [STYLE] [FAST REVIEW] UI Touchups

- client/src/pages/Login.jsx
Typewriter effect on login button!
> [STYLE] [FAST REVIEW]  Revamp login page

- client/src/components/Workout/GuidedExercise.jsx
- client/src/components/Workout/GuidedWorkout.jsx
- client/src/components/Workout/NumberDial.jsx
- client/src/components/Workout/WorkoutSelector.jsx
Just swaps out an incorrect conditional render. Also change CalorieDial to NumberDial.
> [BUG] Fix incorrect conditional in GuidedWorkout + Refactor 

- client/src/components/Home/PlanView/NoSchedule.jsx
- client/src/components/Home/StatsView/NoStatsView.jsx
- client/src/components/Home/StatsView/StatsView.jsx
- client/src/components/Home/WorkoutTable/NoWorkoutTable.jsx
- client/src/components/Home/WorkoutTable/WorkoutTable.jsx
Before:
After (ignore GIF colors):
> [STYLE] [FAST REVIEW]: Improve dashboard UX

- client/src/components/Workout/GuidedExercise.jsx
- client/src/components/Workout/VoiceRecognition/Dictaphone.jsx
Before the control center was flashing between a single icon and multiple icons.
> [BUG] Fix rendering problem in GuidedExercise control center

- client/src/components/Profile/ScheduleHistory/ScheduleHistory.jsx
- server/src/controllers/userProfileController.js
Changes:
- When a user regenerates their schedules and goes to the schedule history page before the request completes, the new schedule is undefined and causes page to break. Bug has been fixed.
- Changed the retrieval of the schedule history from mongodb to use `aggregate` to improve efficiency
-  Reduces the number of db queries required by one
-  Pagination and sorting are handled in the db, only the necessary number of rows are retrieved
> Schedule History bug fix & efficiency improvement

- client/src/components/common/RelativeSpinner.jsx
- client/src/pages/Login.jsx
Update spinner to align with application theme
> [STYLE][FAST REVIEW] Spinner Styling

- client/src/components/Home/StatsView/ExistingStatsView.jsx
- client/src/components/Home/StatsView/NoStatsView.jsx
- client/src/components/Home/StatsView/StatsView.jsx
- client/src/components/Home/WorkoutTable/WorkoutTable.jsx
> [STYLE][FAST REVIEW] Fix Stats component for responsiveness

- client/src/components/Home/PlanView/ExistingMealSchedule.jsx
- client/src/components/Home/PlanView/ExistingWorkoutSchedule.jsx
PR Summary:
- If 1 set, change "sets" to "set" and remove rest
- If 1 rep, change "reps" to "rep"
- If rest is 0 seconds, change "a ${rest} second rest" to "no rest"
- Proper labelling for meals
Before:
After:
> [STYLE] Improve Grammar for Plans

- client/src/components/Home/WorkoutTable/ExistingWorkoutTable.jsx
- client/src/components/Home/WorkoutTable/WorkoutBrowserCarousel.jsx
- client/src/components/Workout/ExercisesTable.jsx
> feat: implement dashboard exercise table

- client/src/components/Home/ChatArea/ChatBubble.jsx
- client/src/components/Home/ChatArea/util.js
Adjust color
Adjust meal label
> [STYLE] chatarea update

- client/src/components/Home/PlanView/ExistingMealSchedule.jsx
- client/src/components/Home/PlanView/ExistingWorkoutSchedule.jsx
- client/src/components/Home/PlanView/TabbedScheduleView.jsx
* Days of week in tabbed pane
* Regenerate plans button styling to match rest of app
* Tabbed pane text and indicator color
> Days of Week  in Tabbed plan view

- client/src/components/Home/WorkoutTable/WorkoutBrowserCarousel.jsx
- client/src/components/Workout/ExercisesTable.jsx
- client/src/components/Workout/GuidedExercise.jsx
- client/src/components/Workout/GuidedWorkout.jsx
- client/src/components/Workout/NumberDial.jsx
- client/src/components/Workout/VoiceRecognition/Dictaphone.jsx
- client/src/components/Workout/WorkoutCarousel.jsx
- client/src/components/Workout/WorkoutSelector.jsx
- client/src/pages/Workout.jsx
> [BUGS]: cleanup console errors in GuidedWorkout flow

- client/src/components/Workout/GuidedExercise.jsx
- client/src/components/Workout/GuidedWorkout.jsx
- client/src/components/Workout/WorkoutCarousel.jsx
- client/src/components/Workout/WorkoutSelector.jsx
- client/src/pages/Landing.jsx
- client/src/pages/Workout.jsx
> Add responsiveness to landing page and guided workouts

- client/src/pages/About.jsx
> style: accessible colors for about page

- client/src/components/Profile/Forms/Form.jsx
- client/src/components/Profile/Forms/FormDatePicker.jsx
- client/src/components/Profile/Forms/FormMultiInput.jsx
- client/src/components/Profile/Forms/FormMultiSelect.jsx
- client/src/components/Profile/Forms/FormSelect.jsx
- client/src/components/Profile/Forms/FormTextFieldInput.jsx
- client/src/components/Profile/Forms/FormTextWithRadio.jsx
- client/src/components/Profile/Forms/GridInputLabel.jsx
- client/src/components/Profile/Forms/PaperForm.jsx
- client/src/pages/About.jsx
PR Summary:
- Add breakpoints to the Profile page to improve responsiveness
- Fix the About Us page background color when redirected from landing page
- Fix link to Kevin C.'s Github on the About Us page
Before:
After:
> [STYLE][FAST REVIEW] Profile Page Responsiveness / About Us background color

- client/src/pages/Workout.jsx
https://github.com/jakji93/airon-fitness/assets/67628346/99bfd3da-2141-4ea8-bfb1-899210b6db07
> [FAST] add get workouts and meals at workouts page

- client/src/components/Home/ChatArea/ChatArea.jsx
PR Summary:
- Fix typo
- Change styling for height/weight input
Before:
After:
> Fix typo & improve styling for manual input

- client/src/components/Home/ChatArea/ChatArea.jsx
Just this first part of this video
https://github.com/jakji93/airon-fitness/assets/67628346/7988e334-f951-4ce8-ad26-8d4419754ea8
> added spinnner to chat area

- client/src/components/Navbar.jsx
- client/src/pages/About.jsx
1) Add text hover back to the navbar buttons
2) Adjust about page text containere width from 50vw to 75vw
> [STYLE] [FAST REVIEW]  More Touchups

- client/src/components/Profile/Forms/Form.jsx
- client/src/components/Profile/Forms/PaperForm.jsx
> [FAST-REVIEW][BUGFIX] Fix console error for profile page

- client/src/pages/Login.jsx
> added disclaimer for onrender slow loading, for job applications

- client/public/index.html
Metainformation is now properly displayed in message previews (at least I think so, we'll find out once it is live on Render).
> chore: update client index file
